/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.GUIview;

import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamn
 */
public class ViewLogForm extends javax.swing.JPanel {

    /**
     * Creates new form ViewLogForm
     */
    public ViewLogForm() {
        initComponents();
        createFormLanguage();
        
        // code cua ho
//        Vector<Vector> logs=BankGUI.bank.getLogs(BankGUI.curAcc.getAccNo());
//        Vector td= new Vector(); td.add("ID");td.add("Time");
//        td.add("Type");td.add("Amount");td.add("Post Bal");
//        DefaultTableModel dtm= new DefaultTableModel(logs,td);
//        logTbl.setModel(dtm);
    }

    // return default = ?
    // vietnamese => bundle = ///
    // english => bundle = ///
    
    private String returnBundle() {
        String bundle;
        if ( BankGUI.localeToString().equals("vi_VN") ) {
            bundle = "viewlog/Bundle_vi_VN_viewlog";
        }
        else {
            bundle = "viewlog/Bundle_en_US_viewlog";
        }
        return bundle;
    }
    
    private void createFormLanguage() {
        String bundle = returnBundle();
        ResourceBundle viewlog = ResourceBundle.getBundle(bundle, BankGUI.checkLocale() );
        ViewLogForm.jLabel2.setText(viewlog.getString("ViewLogForm.jLabel2.text"));
        // clear cache
        ResourceBundle.clearCache();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("viewlog/Bundle_vi_VN_viewlog"); // NOI18N
        jLabel2.setText(bundle.getString("ViewLogForm.jLabel2.text")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
